import Head from 'next/head';
import { useContext } from 'react';
import { AuthContext } from '../context/authProvider';
import Login from './login';
import MyTask from './myTask';
import { ToastContainer } from 'react-nextjs-toast'


export default function Home() {
  const { user } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user ? <MyTask /> : <Login />}
      </main>
      <ToastContainer position="top-center" />
    </>
  )
}